<?php
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Method not allowed.';
    exit;
}

$raw = $_POST['plan_data'] ?? '';
$data = json_decode($raw, true);
if (!is_array($data)) {
    http_response_code(400);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Invalid plan data.';
    exit;
}

$fpdfPath = __DIR__ . '/fpdf/fpdf.php';
if (!file_exists($fpdfPath)) {
    http_response_code(500);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'FPDF library not found. Make sure /fpdf/fpdf.php exists beside this file.';
    exit;
}

require_once $fpdfPath;

function safe_text($value): string {
    $text = is_scalar($value) ? (string) $value : '';
    $text = preg_replace('/\s+/u', ' ', trim($text));
    $converted = @iconv('UTF-8', 'windows-1252//TRANSLIT//IGNORE', $text);
    return $converted !== false ? $converted : $text;
}

function safe_lines($items): array {
    if (!is_array($items)) {
        return [];
    }
    $out = [];
    foreach ($items as $item) {
        $line = safe_text($item);
        if ($line !== '') {
            $out[] = $line;
        }
    }
    return $out;
}

function safe_phone_link($number): string {
    $clean = preg_replace('/[^0-9+]/', '', (string) $number);
    if ($clean === '') {
        return '';
    }
    if ($clean[0] !== '+') {
        $clean = '+' . ltrim($clean, '+');
    }
    return 'tel:' . $clean;
}

function scenario_palette(string $scenario): array {
    $key = strtolower(trim($scenario));
    return match ($key) {
        'flood' => [
            'accent' => [95, 216, 255],
            'soft' => [231, 248, 255],
            'deep' => [18, 64, 97],
            'chip' => [34, 112, 163],
        ],
        'fire' => [
            'accent' => [255, 138, 61],
            'soft' => [255, 244, 236],
            'deep' => [120, 54, 20],
            'chip' => [206, 96, 35],
        ],
        'storm' => [
            'accent' => [151, 124, 255],
            'soft' => [242, 238, 255],
            'deep' => [77, 58, 143],
            'chip' => [111, 85, 201],
        ],
        default => [
            'accent' => [103, 215, 156],
            'soft' => [236, 250, 244],
            'deep' => [28, 97, 72],
            'chip' => [44, 140, 104],
        ],
    };
}

function severity_palette(string $severity): array {
    $key = strtolower(trim($severity));
    return match ($key) {
        'low' => [
            'accent' => [66, 198, 112],
            'soft' => [235, 250, 239],
            'deep' => [28, 108, 56],
        ],
        'moderate' => [
            'accent' => [255, 190, 69],
            'soft' => [255, 248, 229],
            'deep' => [132, 91, 0],
        ],
        'high' => [
            'accent' => [255, 138, 61],
            'soft' => [255, 241, 232],
            'deep' => [138, 66, 13],
        ],
        'critical' => [
            'accent' => [255, 78, 78],
            'soft' => [255, 236, 236],
            'deep' => [145, 23, 23],
        ],
        default => [
            'accent' => [113, 192, 143],
            'soft' => [237, 248, 241],
            'deep' => [39, 104, 69],
        ],
    };
}

class HandaVisPlanPDF extends FPDF {
    public array $scenarioPalette = [];
    public array $severityPalette = [];
    public string $scenarioName = 'Scenario';
    public string $severityName = 'Severity';

    public function Header(): void {
        $this->SetFillColor(11, 20, 33);
        $this->Rect(0, 0, 210, 18, 'F');

        $accent = $this->scenarioPalette['accent'] ?? [95, 216, 255];
        $this->SetFillColor($accent[0], $accent[1], $accent[2]);
        $this->Rect(0, 0, 210, 2.5, 'F');

        $this->SetFont('Helvetica', 'B', 11);
        $this->SetTextColor(255, 255, 255);
        $this->SetXY(14, 6);
        $this->Cell(90, 6, 'HANDAVis Emergency Plan', 0, 0, 'L');

        $this->SetFont('Helvetica', '', 8.5);
        $this->SetTextColor(200, 224, 241);
        $this->Cell(0, 6, safe_text($this->scenarioName . ' • ' . $this->severityName), 0, 0, 'R');

        $this->Ln(8);
    }

    public function Footer(): void {
        $this->SetY(-12);
        $this->SetDrawColor(214, 225, 236);
        $this->Line(14, $this->GetY(), 196, $this->GetY());
        $this->SetY(-10);
        $this->SetFont('Helvetica', '', 8.5);
        $this->SetTextColor(110, 118, 133);
        $this->Cell(0, 5, 'Generated by HANDAVis - Page ' . $this->PageNo(), 0, 0, 'C');
    }
}

function ensure_space(FPDF $pdf, float $needed): void {
    if ($pdf->GetY() + $needed > ($pdf->GetPageHeight() - 16)) {
        $pdf->AddPage();
    }
}

function fill_rect(FPDF $pdf, float $x, float $y, float $w, float $h, array $rgb): void {
    $pdf->SetFillColor($rgb[0], $rgb[1], $rgb[2]);
    $pdf->Rect($x, $y, $w, $h, 'F');
}

function draw_chip(FPDF $pdf, float $x, float $y, float $w, string $text, array $fill, array $textColor = [255, 255, 255]): void {
    $pdf->SetXY($x, $y);
    $pdf->SetFillColor($fill[0], $fill[1], $fill[2]);
    $pdf->SetTextColor($textColor[0], $textColor[1], $textColor[2]);
    $pdf->SetFont('Helvetica', 'B', 8.5);
    $pdf->Cell($w, 7, safe_text($text), 0, 0, 'C', true);
}

function draw_hero(FPDF $pdf, array $data, array $scenarioPal, array $severityPal): void {
    $x = 14;
    $y = 24;
    $w = 182;
    $h = 36;

    fill_rect($pdf, $x, $y, $w, $h, [15, 24, 38]);
    fill_rect($pdf, $x, $y, 5.5, $h, $scenarioPal['accent']);

    $pdf->SetXY($x + 10, $y + 6);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Helvetica', 'B', 18);
    $pdf->Cell(98, 8, safe_text(($data['scenario'] ?? 'Emergency') . ' Response Plan'), 0, 1, 'L');

    $pdf->SetX($x + 10);
    $pdf->SetFont('Helvetica', '', 9.5);
    $pdf->SetTextColor(201, 222, 239);
    $subtitle = ($data['location'] ?? '') . ' • ' . ($data['timeWindow'] ?? '') . ' • Generated ' . ($data['generatedAt'] ?? date('Y-m-d H:i:s'));
    $pdf->Cell(110, 6, safe_text($subtitle), 0, 0, 'L');

    draw_chip($pdf, $x + $w - 50, $y + 7, 38, strtoupper((string) ($data['severity'] ?? 'Severity')), $severityPal['accent']);
    draw_chip($pdf, $x + $w - 50, $y + 18, 38, strtoupper((string) ($data['scenario'] ?? 'Scenario')), $scenarioPal['chip']);

    $pdf->SetDrawColor(58, 81, 103);
    $pdf->Line($x + 10, $y + 27, $x + 120, $y + 27);

    $pdf->SetXY($x + 10, $y + 29);
    $pdf->SetTextColor(154, 187, 212);
    $pdf->SetFont('Helvetica', '', 8.5);
    $pdf->Cell(120, 5, 'Prepared for quick reference, route guidance, and local emergency response coordination.', 0, 0, 'L');

    $pdf->SetY($y + $h + 8);
}

function draw_section_title(FPDF $pdf, string $title, array $accent): void {
    ensure_space($pdf, 12);
    $y = $pdf->GetY();
    fill_rect($pdf, 14, $y, 4, 8, $accent);
    $pdf->SetXY(21, $y + 0.5);
    $pdf->SetFont('Helvetica', 'B', 12);
    $pdf->SetTextColor(20, 33, 46);
    $pdf->Cell(0, 7, safe_text($title), 0, 1, 'L');
    $pdf->Ln(1.5);
}

function draw_metric_box(FPDF $pdf, float $x, float $y, float $w, string $label, string $value, array $fill, array $valueColor): void {
    fill_rect($pdf, $x, $y, $w, 19, $fill);
    $pdf->SetDrawColor(223, 232, 242);
    $pdf->Rect($x, $y, $w, 19);

    $pdf->SetXY($x + 4, $y + 3);
    $pdf->SetFont('Helvetica', 'B', 8.5);
    $pdf->SetTextColor(102, 118, 134);
    $pdf->Cell($w - 8, 4.5, safe_text($label), 0, 1, 'L');

    $pdf->SetX($x + 4);
    $pdf->SetFont('Helvetica', 'B', 12.5);
    $pdf->SetTextColor($valueColor[0], $valueColor[1], $valueColor[2]);
    $pdf->Cell($w - 8, 6, safe_text($value), 0, 0, 'L');
}

function draw_info_row(FPDF $pdf, string $label, string $value, array $accent): void {
    if ($value === '') {
        return;
    }
    ensure_space($pdf, 8);
    $x = 14;
    $y = $pdf->GetY();
    $pdf->SetDrawColor(232, 238, 244);
    $pdf->Line($x, $y + 7.5, 196, $y + 7.5);

    $pdf->SetXY($x, $y + 1);
    $pdf->SetFont('Helvetica', 'B', 9);
    $pdf->SetTextColor($accent[0], $accent[1], $accent[2]);
    $pdf->Cell(38, 5, safe_text($label), 0, 0, 'L');

    $pdf->SetFont('Helvetica', '', 10);
    $pdf->SetTextColor(43, 52, 61);
    $pdf->SetXY($x + 38, $y + 0.2);
    $pdf->MultiCell(144, 5.6, safe_text($value), 0, 'L');
    $pdf->Ln(1.5);
}

function draw_bullet_list(FPDF $pdf, array $items, array $bulletColor): void {
    if (!$items) {
        draw_info_row($pdf, 'Status', 'No items available.', $bulletColor);
        return;
    }
    foreach ($items as $item) {
        ensure_space($pdf, 8);
        $x = 14;
        $y = $pdf->GetY();
        $pdf->SetXY($x, $y + 0.5);
        $pdf->SetFont('Helvetica', 'B', 12);
        $pdf->SetTextColor($bulletColor[0], $bulletColor[1], $bulletColor[2]);
        $pdf->Cell(6, 5, chr(149), 0, 0, 'C');

        $pdf->SetFont('Helvetica', '', 10);
        $pdf->SetTextColor(43, 52, 61);
        $pdf->SetXY($x + 7, $y);
        $pdf->MultiCell(175, 5.7, safe_text($item), 0, 'L');
        $pdf->Ln(0.8);
    }
}

function draw_sub_card(FPDF $pdf, string $title, array $titleFill, callable $content): void {
    ensure_space($pdf, 18);
    $x = 14;
    $y = $pdf->GetY();
    fill_rect($pdf, $x, $y, 182, 8, $titleFill);
    $pdf->SetXY($x + 4, $y + 1.3);
    $pdf->SetFont('Helvetica', 'B', 10);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(174, 5, safe_text($title), 0, 1, 'L');
    $pdf->Ln(1.5);
    $content($pdf);
    $pdf->Ln(2);
}

function draw_place_entry(FPDF $pdf, array $place, array $scenarioPal): void {
    $name = safe_text($place['name'] ?? 'Support Point');
    $address = safe_text($place['address'] ?? '');
    $phone = safe_text($place['phone'] ?? '');
    $note = safe_text($place['note'] ?? '');

    ensure_space($pdf, 18);
    $x = 14;
    $y = $pdf->GetY();
    fill_rect($pdf, $x, $y, 182, 1.6, $scenarioPal['accent']);

    $pdf->SetXY($x, $y + 3);
    $pdf->SetFont('Helvetica', 'B', 10.5);
    $pdf->SetTextColor(20, 33, 46);
    $pdf->Cell(0, 5, $name, 0, 1, 'L');

    if ($address !== '') {
        $pdf->SetX($x);
        $pdf->SetFont('Helvetica', '', 9.5);
        $pdf->SetTextColor(78, 92, 106);
        $pdf->MultiCell(182, 5, $address, 0, 'L');
    }

    if ($phone !== '' || $note !== '') {
        $pdf->SetX($x);
        $pdf->SetFont('Helvetica', '', 9);
        $pdf->SetTextColor(96, 107, 120);
        $info = [];
        if ($phone !== '') {
            $info[] = 'Desk: ' . $phone;
        }
        if ($note !== '') {
            $info[] = $note;
        }
        $pdf->MultiCell(182, 4.8, safe_text(implode(' • ', $info)), 0, 'L');
    }

    $pdf->Ln(1);
}

function draw_contact_entry(FPDF $pdf, array $contact, array $severityPal): void {
    $name = safe_text($contact['name'] ?? 'Emergency Contact');
    $number = safe_text($contact['number'] ?? '');
    $detail = safe_text($contact['detail'] ?? '');
    $telLink = safe_phone_link($number);

    ensure_space($pdf, 16);
    $x = 14;
    $y = $pdf->GetY();
    fill_rect($pdf, $x, $y, 182, 1.6, $severityPal['accent']);

    $pdf->SetXY($x, $y + 3);
    $pdf->SetFont('Helvetica', 'B', 10.5);
    $pdf->SetTextColor(20, 33, 46);
    $pdf->Cell(0, 5, $name, 0, 1, 'L');

    $pdf->SetX($x);
    $pdf->SetFont('Helvetica', '', 9.5);
    $pdf->SetTextColor(46, 79, 123);
    if ($number !== '') {
        $pdf->Cell(70, 5, $number, 0, 0, 'L', false, $telLink ?: '');
    }
    $pdf->SetTextColor(96, 107, 120);
    if ($detail !== '') {
        $pdf->MultiCell(112, 5, $detail, 0, 'L');
    } else {
        $pdf->Ln(5);
    }

    if ($telLink !== '') {
        $pdf->SetX($x);
        $pdf->SetFont('Helvetica', 'B', 8.5);
        $pdf->SetTextColor($severityPal['deep'][0], $severityPal['deep'][1], $severityPal['deep'][2]);
        $pdf->Cell(34, 4.5, 'Tap to call', 0, 1, 'L', false, $telLink);
    }

    $pdf->Ln(1);
}

$decision = is_array($data['decision'] ?? null) ? $data['decision'] : [];
$safePlaces = is_array($data['safePlaces'] ?? null) ? $data['safePlaces'] : [];
$contacts = is_array($data['contacts'] ?? null) ? $data['contacts'] : [];
$route = is_array($data['route'] ?? null) ? $data['route'] : [];
$scenarioName = (string) ($data['scenario'] ?? 'Scenario');
$severityName = (string) ($data['severity'] ?? 'Severity');

$scenarioPal = scenario_palette($scenarioName);
$severityPal = severity_palette($severityName);

$pdf = new HandaVisPlanPDF();
$pdf->scenarioPalette = $scenarioPal;
$pdf->severityPalette = $severityPal;
$pdf->scenarioName = $scenarioName;
$pdf->severityName = $severityName;
$pdf->SetTitle(safe_text($scenarioName . ' Emergency Plan'));
$pdf->SetAuthor('HANDAVis');
$pdf->SetMargins(14, 22, 14);
$pdf->SetAutoPageBreak(true, 14);
$pdf->AddPage();

draw_hero($pdf, $data, $scenarioPal, $severityPal);

draw_section_title($pdf, 'Situation Assessment', $scenarioPal['accent']);
$metricY = $pdf->GetY();
draw_metric_box($pdf, 14, $metricY, 56, 'Risk Score', safe_text((string) ($decision['score'] ?? 'N/A')), $scenarioPal['soft'], $severityPal['deep']);
draw_metric_box($pdf, 77, $metricY, 56, 'Status', safe_text((string) ($decision['status'] ?? 'Monitoring')), $scenarioPal['soft'], $scenarioPal['deep']);
draw_metric_box($pdf, 140, $metricY, 56, 'Action Priority', safe_text((string) ($decision['actionPriority'] ?? 'Review')), $scenarioPal['soft'], $scenarioPal['deep']);
$pdf->SetY($metricY + 24);

draw_info_row($pdf, 'Action Note', (string) ($decision['actionNote'] ?? ''), $scenarioPal['accent']);
draw_info_row($pdf, 'Movement Advice', trim((string) ($decision['movement'] ?? '') . ' - ' . (string) ($decision['movementNote'] ?? '')), $scenarioPal['accent']);
draw_info_row($pdf, 'Priority Safe Place', (string) ($decision['safePlace'] ?? ''), $scenarioPal['accent']);
draw_info_row($pdf, 'Primary Contact', (string) ($decision['primaryContact'] ?? ''), $scenarioPal['accent']);
draw_info_row($pdf, 'Why This Matters', (string) ($decision['whyNow'] ?? ''), $scenarioPal['accent']);
draw_info_row($pdf, 'Exposure', (string) ($decision['exposure'] ?? ''), $scenarioPal['accent']);
draw_info_row($pdf, 'Next Step', (string) ($decision['nextStep'] ?? ''), $scenarioPal['accent']);

draw_sub_card($pdf, 'Plan Snapshot', $scenarioPal['chip'], function (FPDF $pdf) use ($data, $severityPal, $scenarioPal): void {
    draw_info_row($pdf, 'Scenario', (string) ($data['scenario'] ?? ''), $scenarioPal['accent']);
    draw_info_row($pdf, 'Location', (string) ($data['location'] ?? ''), $scenarioPal['accent']);
    draw_info_row($pdf, 'Severity', (string) ($data['severity'] ?? ''), $severityPal['accent']);
    draw_info_row($pdf, 'Time Window', (string) ($data['timeWindow'] ?? ''), $scenarioPal['accent']);
    draw_info_row($pdf, 'Generated', (string) ($data['generatedAt'] ?? date('Y-m-d H:i:s')), $scenarioPal['accent']);
});

if ($route) {
    draw_sub_card($pdf, 'Route Guidance', $severityPal['accent'], function (FPDF $pdf) use ($route, $scenarioPal): void {
        draw_info_row($pdf, 'Destination', (string) ($route['destination'] ?? ''), $scenarioPal['accent']);
        draw_info_row($pdf, 'Address', (string) ($route['address'] ?? ''), $scenarioPal['accent']);
        draw_info_row($pdf, 'Estimated Travel Time', (string) ($route['eta'] ?? ''), $scenarioPal['accent']);
        draw_info_row($pdf, 'Distance', (string) ($route['distance'] ?? ''), $scenarioPal['accent']);
        draw_info_row($pdf, 'Route Note', (string) ($route['note'] ?? ''), $scenarioPal['accent']);
    });
}

draw_section_title($pdf, 'Expected Impact', $severityPal['accent']);
draw_bullet_list($pdf, safe_lines($data['impacts'] ?? []), $severityPal['accent']);

$pdf->Ln(2);
draw_section_title($pdf, 'What To Do Now', $scenarioPal['accent']);
draw_bullet_list($pdf, safe_lines($data['actions'] ?? []), $scenarioPal['accent']);

$pdf->Ln(2);
draw_section_title($pdf, 'Nearest Safe Places / Support Points', $scenarioPal['accent']);
if ($safePlaces) {
    foreach ($safePlaces as $place) {
        if (is_array($place)) {
            draw_place_entry($pdf, $place, $scenarioPal);
        }
    }
} else {
    draw_info_row($pdf, 'Status', 'No safe place data was included in this export.', $scenarioPal['accent']);
}

$pdf->Ln(2);
draw_section_title($pdf, 'Emergency Contacts', $severityPal['accent']);
if ($contacts) {
    foreach ($contacts as $contact) {
        if (is_array($contact)) {
            draw_contact_entry($pdf, $contact, $severityPal);
        }
    }
} else {
    draw_info_row($pdf, 'Status', 'No emergency contacts were included in this export.', $severityPal['accent']);
}

$pdf->Ln(2);
draw_sub_card($pdf, 'Reminder', [11, 20, 33], function (FPDF $pdf): void {
    $pdf->SetFont('Helvetica', '', 10);
    $pdf->SetTextColor(43, 52, 61);
    $pdf->MultiCell(182, 5.7, safe_text('Use this PDF as a quick planning guide only. Follow official PAGASA, LGU, DRRMO, BFP, or evacuation instructions immediately if they conflict with this plan or if conditions change on the ground.'));
});

$filename = preg_replace('/[^A-Za-z0-9._-]+/', '-', (string) ($data['filename'] ?? 'handavis-plan.pdf'));
if ($filename === '' || substr($filename, -1) === '.') {
    $filename = 'handavis-plan.pdf';
}
if (strtolower(substr($filename, -4)) !== '.pdf') {
    $filename .= '.pdf';
}

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '"');
$pdf->Output('I', $filename);
exit;
